
language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - rm -rf node_modules
  - npm update
  - npm upgrade
  - npm install -g @angular/cli
  - npm install

script:
  - ng build
  - ng test --watch=false

sudo: required

services:
  - docker

before_install:
  - docker build -t justforexwa/justforex-main .
  - docker run -d -p 80:4200 justforexwa/justforex-main

after_success:
   - docker login -u="justforexwa" -p="ahdgmypnd20"
   - docker push justforexwa/justforex-main
